services:
  bot:
    image: ghcr.io/maxwellpower/mm-standup-bot:latest
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: standupbot
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
